[package]
name = "rustdoc"
edition = "2021"
version = "0.0.0"
publish = false

[workspace]
members = []

[dependencies.gnuplotter]
version = "=0.1.0"
features = []

[lib]
path = "lib.rs"
required-features = []
