on: [push]

name: Tests

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install gnuplot
        run: sudo apt-get install -y gnuplot
      - name: Testing all targets (except documentation)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets
      - name: Testing documentation
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc
      - name: Build a release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features