on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-alpha'
      - 'v*.*.*-beta'
      - 'v*.*.*-rc.*'

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install gnuplot
        run: sudo apt-get install -y gnuplot
      - name: Testing all targets (except documentation)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets
      - name: Testing documentation
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc
#      - name: Check semver
#        uses: obi1kenobi/cargo-semver-checks-action@v2
      - name: Publish gnuplotter_core to crates.io
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --all-features --allow-dirty -p gnuplotter_core --token=${{secrets.CRATESIO}}
      - name: Publish gnuplotter_macro to crates.io
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --all-features --allow-dirty -p gnuplotter_macros --token=${{secrets.CRATESIO}}
      - name: Publish main library to crates.io
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --all-features --allow-dirty -p gnuplotter --token=${{secrets.CRATESIO}}