on:
  push:
    # Pattern matched against refs/tags
    # e.g. v0.1.0-alpha, v1.0.0-beta, v1.0.0-rc.1
    tags:
      - '^v[0-9\.]+/**$'

name: CI

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --release --all-features --token=${{secrets.CRATESIO}}